---
title: "writing_functions"
author: "Anni Wang"
date: "2024-10-24"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(rvest)
```

```{r}
x_vec=rnorm(n=25, mean=10, sd=3.5)
(x_vec - mean(x_vec)) / sd(x_vec)
```
```{r}
z_scores=function(x){
  if (!is.numeric(x)) {
    stop("x need to be numeric")
  }
  if (length(x)<5){
    stop("you need at least 5 to compare the z score")
  }
  z=(x-mean(x))/sd(x)
  return(z)
}
z_scores(x=x_vec)
```
```{r,error=TRUE}
#does this always work
z_scores(x="my","name")
z_scores(x=3)
z_scores(x=x_vec)

```

```{r}
mean_and_sd=function(x){
  mean_x=mean(x)
  sd_x=sd(x)
  
  out_df=
    tibble(
      mean=mean_x,
      sd=sd_x
    )
  return(out_df)
}
mean_and_sd(x_vec)
```

```{r}
sim_df=
  tibble(
    x=rnorm(30,10,5)
  )
sim_df|>
  summarise(
    mean=mean(x),
    sd=sd(x)
  )
```
```{r}
#simulation function to check sample mean and sd
sim_mean_sd=function(sample_size, true_mean,true_sd){
  sim_df=
  tibble(
    x=rnorm(sample_size,true_mean,true_sd)
  )
out_df=sim_df|>
  summarise(
    mean=mean(x),
    sd=sd(x)
  )
return(out_df)
  
}
sim_mean_sd(sample_size=30, true_mean=4, true_sd=12)

```
```{r}
#revist lord ds
fellowship_df <- read_excel("LotR_Words.xlsx", range = "B3:D6")|>
  mutate(movie="fellowship")|>
  janitor::clean_names()

two_towers<-  read_excel("LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")|>
  janitor::clean_names()

return_king =  read_excel("LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")|>
  janitor::clean_names()
```

```{r}
#function instead

lotr_import=function(cell_range,movie_title){
  movie_df <- read_excel("LotR_Words.xlsx", range = cell_range)|>
  mutate(movie=movie_title)|>
  janitor::clean_names()|>
    pivot_longer(
      female:male,
      names_to = "sex",
      values_to = "words"
    )|>
    select(movie,everything())
  
  
  return(movie_df)
}
lotr_df=
  bind_rows(
lotr_import( "B3:D6", "fellowship"),
lotr_import("F3:H6", "two_towers"),
lotr_import("J3:L6", "return_king")
    
  )

```


```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
marj_table=
  nsduh_html|>
  html_table()|>
  nth(1)|>
  slice(-1)|>
  mutate(drug="marj")

cocaine_table=
  nsduh_html|>
  html_table()|>
  nth(4)|>
  slice(-1)|>
  mutate(drug="cocaine")

heroin_table=
  nsduh_html|>
  html_table()|>
  nth(5)|>
  slice(-1)|>
  mutate(drug="heroin")

nsduh_table_format=function(html,table_num,table_name){
  out_table=
    nsduh_html|>
    html_table()|>
    nth(table_num)|>
    slice(-1)|>
    mutate(drug=table_name)|>
    select(-contains("P Value"))
  return(out_table)
}
bind_rows(
   nsduh_table_format(html=nsduh_html,1,"marj"),
   nsduh_table_format(html=nsduh_html,4,"cocaine"),
   nsduh_table_format(html=nsduh_html,5,"heroin")
  )
```

